config/routes.rb
class SubdomainRequired
  def self.matches?(request)
    request.subdomain.present? && request.subdomain != "www"
  end
end

Rails.application.routes.draw do
  devise_for :users
  resource :account, only: [:new, :create]
  resources :children, only: [:index, :create]
  get 'child/new', to: 'children#new', as: 'new_child'
  get 'child/:id', to: 'children#show', as: 'child_show'
  resource :attachment, only: [:new, :create]
  get 'attachment/:id', to: 'attachments#show', as: 'attachment_show'
  resource :album, only: [:new, :create]
  get 'album/:id', to: 'albums#show', as: 'album_show'

  constraints SubdomainRequired do
    root to: 'dashboards#show', as: 'subdomain_root'
  end

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  include ActiveModel::Serializers::JSON
  validates :name, :subdomain, presence: true
  validates :subdomain,
            format: { with: /\A[a-z][a-z0-9\-]+[a-z0-9]\Z/ },
            uniqueness: true
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  has_one :owner_membership, -> { where(role: 'owner') }, class_name: 'Membership'
  has_one :owner, through: :owner_membership, source: :user, class_name: 'User'
  accepts_nested_attributes_for :owner
  has_many :attachments
  has_many :albums
  has_many :children
end

app/models/album.rb
class Album < ApplicationRecord
  include ActiveModel::Serializers::JSON
  belongs_to :account
  belongs_to :user
  has_many :attachments
  accepts_nested_attributes_for :attachments, reject_if: proc { |attrs| attrs['attachment_upload'].blank? && attrs['attachment_upload_cache'].blank? }
  
  def self.by_recent
    order(created_at: :desc, id: :desc)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  include ActiveModel::Serializers::JSON
  validates_presence_of :attachment_upload, :status

  mount_uploader :attachment_upload, AttachmentUploader

  enum status: { "Pending" => 0, "Approved" => 1 }

  belongs_to :account
  belongs_to :user
  belongs_to :album, optional: true
  has_many :child_tags, dependent: :destroy
  has_many :children, through: :child_tags

  def self.by_recent
    order(created_at: :desc, id: :desc)
  end
end

app/models/child.rb
class Child < ApplicationRecord
  belongs_to :account
  has_many :child_tags, dependent: :destroy
  has_many :attachments, through: :child_tags

  validates :pronoun, inclusion: { in: PRONOUNS }
end

app/models/child_tag.rb
class ChildTag < ApplicationRecord
  belongs_to :account
  belongs_to :child
  belongs_to :attachment
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :account
  belongs_to :user

  validates :account, :user, presence: true
  validates :role, inclusion: { in: SYSTEM_ROLES }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :memberships, dependent: :destroy
  has_many :accounts, through: :memberships
  has_many :attachments
  has_many :albums
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
    @account = Account.new
    @account.owner = User.new #!
  end

  def create
    @account = Account.new(account_params)
    @account.owner = User.new(user_params)

    if @account.save
      redirect_to root_url
    else
      render :new
    end
  end

  private

  def account_params
    params.require(:account).permit(:name, :subdomain)
  end

  def user_params
    params.require(:account).require(:owner_attributes).permit(:email, :first_name, :last_name, :password, :password_confirmation)
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_account
  before_action :require_account!
  before_action :authenticate_user!

  def show
    @album = @account.albums.includes(:attachments).find(params[:id])
  end

  def new
    @album = @account.albums.new
    4.times { @album.attachments.build }
  end

  def create
    @album = @account.albums.new(album_params)

    if @album.save
      redirect_to subdomain_root_url, notice: 'Attachment was successfully saved.'
    else
      render :new
    end
  end

  private

  def set_account
    @account = Account.find_by(subdomain: request.subdomain)
  end

  def album_params
    params.require(:album).permit(:user_id, :title, :description, attachments_attributes: [:id, :user_id, :account_id, :attachment_upload, :content_type, :alt, :caption, :status])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :redirect_to_subdomain

  private

  def require_account!
    redirect_to root_url(subdomain: "www") if @account.nil?
  end

  def redirect_to_subdomain
    return unless user_signed_in?

    if request.subdomain.blank?
      if current_user.accounts.any?
        redirect_to root_url(subdomain: current_user.accounts.first.subdomain)
      end
    else
      unless current_user.accounts.pluck(:subdomain).include?(request.subdomain)
        redirect_to root_url(subdomain: current_user.accounts.first.subdomain)
      end
    end
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_account
  before_action :require_account!
  before_action :authenticate_user!

  def show
    @attachment = @account.attachments.find(params[:id])
  end

  def new
    @attachment = @account.attachments.new
  end

  def create
    @attachment = @account.attachments.new(attachment_params)

    if @attachment.save
      redirect_to subdomain_root_url, notice: 'Attachment was successfully saved.'
    else
      render :new
    end
  end

  private
  
  def set_account
    @account = Account.find_by(subdomain: request.subdomain)
  end

  def attachment_params
    params.require(:attachment).permit(:user_id, :account_id, :attachment_upload, :content_type, :alt, :caption, :status)
  end
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_action :set_account
  before_action :require_account!
  before_action :authenticate_user!

  def index
    @children = @account.children.all
  end

  def show
    @child = @account.children.includes(:attachments).find(params[:id])
  end

  def new
    @child = @account.children.new
  end

  def create
    @child = @account.children.new(child_params)

    if @child.save
      redirect_to children_path, notice: "#{@child.first_name} was successfully added."
    else
      render :new
    end
  end

  private

  def set_account
    @account = Account.find_by(subdomain: request.subdomain)
  end

  def child_params
    params.require(:child).permit(:first_name, :birthdate, :pronoun)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @account = { account: Account.includes(:attachments, albums: :attachments).find_by(subdomain: request.subdomain).serializable_hash(include: [:attachments, albums: { include: :attachments }]) }[:account]
    @attachments = @account['attachments']
    @albums = @account['albums']
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/accounts/new.html.haml
= form_for @account, url: account_path do |f|
  - if @account.errors.any?
    %h2= "#{ pluralize @account.errors.count, 'error' } prevented this account from being saved:"
    %ul
      - @account.errors.full_messages.each do |message|
        %li= message
  = f.label :name
  = f.text_field :name
  = f.label :subdomain
  = f.text_field :subdomain
  = f.fields_for :owner do |fo|
    = fo.label :email
    = fo.email_field :email
    = fo.label :first_name
    = fo.text_field :first_name
    = fo.label :last_name
    = fo.text_field :last_name
    = fo.label :password
    = fo.password_field :password
    = fo.label :password_confirmation
    = fo.password_field :password_confirmation
  = f.submit
      

app/views/albums/new.html.haml
= form_for @album, url: album_path do |f|
  - if @album.errors.any?
    %h2= "#{ pluralize @album.errors.count, 'error' } prevented this album from being saved:"
    %ul
      - @album.errors.full_messages.each do |message|
        %li= message
  = f.hidden_field :user_id, value: current_user.id
  = f.label :title
  = f.text_field :title
  = f.label :description
  = f.text_area :description
  = f.fields_for :attachments, @album.attachments do |attachment|
    = attachment.hidden_field :account_id, value: @album.account.id
    = attachment.hidden_field :user_id, value: current_user.id
    = attachment.label :attachment_upload
    = attachment.file_field :attachment_upload
    = attachment.label :alt
    = attachment.text_field :alt
    = attachment.label :caption
    = attachment.text_field :caption
    = attachment.hidden_field :status, value: "Approved"
  = f.submit
= link_to "Cancel", subdomain_root_url

app/views/albums/show.html.haml
%h1= @album.title if @album.title
%p= @album.description if @album.description
- @album.attachments.each do |album_attachment|
  = link_to attachment_show_path(album_attachment) do
    %figure.thumbnail
      - if album_attachment.content_type.include? 'image'
        = image_tag album_attachment.attachment_upload.thumbnail, alt: album_attachment.alt, class: 'thumbnail__image'
      - elsif album_attachment.content_type.include? 'video'
        = video_tag album_attachment.attachment_upload, controls: true, class: 'thumbnail__video'
      %figcaption.thumbnail__caption= album_attachment.caption
= link_to 'Back to dashboard', subdomain_root_url

app/views/attachments/new.html.haml
= form_for @attachment, url: attachment_path do |f|
  - if @attachment.errors.any?
    %h2= "#{ pluralize @attachment.errors.count, 'error' } prevented this attachment from being saved:"
    %ul
      - @attachment.errors.full_messages.each do |message|
        %li= message
  = f.hidden_field :user_id, value: current_user.id
  = f.label :attachment_upload, "Select image"
  = f.file_field :attachment_upload
  = f.label :alt
  = f.text_field :alt
  = f.label :caption
  = f.text_field :caption
  = f.hidden_field :status, value: "Approved"
  = f.submit
= link_to "Cancel", subdomain_root_url

app/views/attachments/show.html.haml
- if @attachment.content_type.include? 'image'
  = image_tag @attachment.attachment_upload.thumbnail, alt: @attachment.alt
- elsif @attachment.content_type.include? 'video'
  = video_tag @attachment.attachment_upload, controls: true
%blockquote= @attachment.caption
= link_to 'Back to dashboard', subdomain_root_url

app/views/children/index.html.haml
%h1= 'Children'
%ul
  - @children.each do |child|
    %li
      = link_to child_show_path(child) do
        = child.first_name
= link_to 'Add child', new_child_path

app/views/children/new.html.haml
= form_for @child do |f|
  - if @child.errors.any?
    %h2= "#{ pluralize @child.errors.count, 'error' } prevented this attachment from being saved:"
    %ul
      - @child.errors.full_messages.each do |message|
        %li= message
  = f.label :first_name
  = f.text_field :first_name
  = f.label :birthdate
  = f.date_field :birthdate
  = f.label :pronoun
  = f.text_field :pronoun
  = f.submit
= link_to "Cancel", subdomain_root_url

app/views/children/show.html.haml
%h1= @child.first_name
%p= @child.birthdate
- @child.attachments.each do |attachment|
  = link_to attachment_show_path(attachment) do
    %figure.thumbnail
      - if attachment.content_type.include? 'image'
        = image_tag attachment.attachment_upload.thumbnail, alt: attachment.alt, class: 'thumbnail__image'
      - elsif attachment.content_type.include? 'video'
        = video_tag attachment.attachment_upload, controls: true, class: 'thumbnail__video'
      %figcaption.thumbnail__caption= attachment.caption
= link_to 'Back to children', children_path

app/views/dashboards/show.html.haml
%h1= "#{@account['name']} Dashboard"
= link_to "Upload photo", new_attachment_path
= link_to "Log out", destroy_user_session_path, method: :delete
%h2= "Recent Uploads"
- @attachments.each do |attachment|
  = link_to attachment_show_path(attachment['id']) do
    %figure.thumbnail
      - if attachment['content_type'].include? 'image'
        = image_tag attachment['attachment_upload'].thumbnail, alt: attachment['alt'], class: 'thumbnail__image'
      - elsif attachment['content_type'].include? 'video'
        = video_tag attachment['attachment_upload'], controls: true, class: 'thumbnail__video'
      %figcaption.thumbnail__caption= attachment['caption']
%h2= "Albums"
= link_to 'Create album', new_album_path
- @albums.each do |album|
  = link_to album_show_path(album['id']) do
    %h3= album['title'] if album['title']
  %p= album['description'] if album['description']
  - album['attachments'].each do |album_attachment|
    = link_to attachment_show_path(album_attachment['id']) do
      %figure.thumbnail
        - if album_attachment['content_type'].include? 'image'
          = image_tag album_attachment['attachment_upload'].thumbnail, alt: album_attachment['alt'], class: 'thumbnail__image'
        - elsif album_attachment['content_type'].include? 'video'
          = video_tag album_attachment['attachment_upload'], controls: true, class: 'thumbnail__video'
        %figcaption.thumbnail__caption= album_attachment['caption']

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Convida
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %p.notice
      = notice
    %p.alert
      = alert
    = yield
    

app/views/pages/home.html.haml
= link_to 'Create new account', new_account_path